### ISSUE TITLE
Time to learn something about **Markdown**~, hoho

### ISSUE THREAD

**Issue by 0xE8551CCB** [CaiShx/learngit#1]
1. Recommended tutorial: [Markdown-Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)
1. You can learn more details from here: [Markdown-Tutorial](https://github.com/LewisVo/Markdown-Tutorial)
1. BTW, you can try it online, cool: [Cmd Markdown](https://www.zybuluo.com/mdeditor)

:-)

**Comment by CaiShx** [comment]
Have done

**Comment by CaiShx** [comment]
Have done~
